version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/test-1"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/test-2"
    schedule:
      interval: "daily"
