name: Approve on pull_request

on:
  pull_request:
  issue_comment:

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@handle-top-level-errors
      with:
        pull-request-number: 3
        github-token: 
