name: Approve on pull_request

on:
  pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      env:
        tok: "${{ secrets.GITHUB_TOKEN }}"
    - uses: hmarr/auto-approve-action@v2
      if: github.actor == 'dependabot[bot]'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
